### PR TITLE
cmake DHS example and cuHE shared lib generation

### PR DESCRIPTION
**Pull request by andreaTP**
I improved a little bit the cmake in order to manage both shared and static library generation.
In DHS cmake there are examples of various way to use the different configurations.

### CODE REVIEW

**Comment by andreaTP** [comment]
Is there anything that prevent this to be merged? should I externalize that compilation settings?

**Comment by WeiDaiWD** [comment]
I got this error when compiling cuHE:

[  5%] Building NVCC (Device) object CMakeFiles/cuHEShared.dir/cuHEShared_generated_Relinearization.cu.o
nvcc fatal   : redefinition of argument 'std'
CMake Error at cuHEShared_generated_Relinearization.cu.o.cmake:207 (message):
  Error generating
  /home/wei/GitHub-Repositories/cuHE/cuhe/CMakeFiles/cuHEShared.dir//./cuHEShared_generated_Relinearization.cu.o

make[2]: **\* [CMakeFiles/cuHEShared.dir/cuHEShared_generated_Relinearization.cu.o] Error 1
make[1]: **\* [CMakeFiles/cuHEShared.dir/all] Error 2
make: **\* [all] Error 2

**Comment by WeiDaiWD** [comment]
I've no idea where to fix. If you can fix it anytime, I'll merge it again. Thx

**Comment by andreaTP** [comment]
When this problem did appear first?
Right after this merge or even before?

**Pull request merged**
