### PR TITLE
Cmake fix

### PR DESCRIPTION
**Pull request by andreaTP**
I targett the redefinition of "std".
Hope this will work, if not please help me reporting the errors and I will fix them on the way.

At this point I think the only different configuration you have is that I recompile NTL as a shared library that is not the default,  This will be managed properly by the cmake file.

If we run into too much trouble, if you agree, I will go for the configuration of a container such as Docker or Vagga to have a reproducible environment.

### CODE REVIEW

**Comment by WeiDaiWD** [comment]
It solves the problem for cuHE.
But I got another error when compiling DHS:
[ 11%] Building NVCC (Device) object CMakeFiles/simpleDHSXor.dir/simpleDHSXor_generated_simple_DHS_xor.cu.o
Scanning dependencies of target simpleDHSXor
make[2]: **\* No rule to make target `libdhsShared.so', needed by`simpleDHSXor'.  Stop.
make[1]: **\* [CMakeFiles/simpleDHSXor.dir/all] Error 2
make: **\* [all] Error 2

**Comment by andreaTP** [comment]
sure, that suppose to have ntl as shared... I'll keep it simpler to let defaults apply.
Give me 5 min!

**Comment by andreaTP** [comment]
Now this will work

**Comment by WeiDaiWD** [comment]
Still got an error:
make[2]: **\* No rule to make target `libdhs.a', needed by`simpleDHSXor'.  Stop.
make[1]: **\* [CMakeFiles/simpleDHSXor.dir/all] Error 2
make: **\* [all] Error 2

I'll try to look into that. You have a good weekend :)

**Comment by WeiDaiWD** [comment]
make[2]: **\* No rule to make target 'libdhs.a', needed by 'simpleDHSXor'. Stop.
make[2]: **\* No rule to make target 'libdhsShared.so', needed by 'simpleDHSXor'. Stop.
I think it cannot find targets if we just link the path of files in 'CMakeLists.txt'.

This works for sure:

> make dhs
> make dhsShared
> make

Could you please look into that? Thx

**Pull request merged**
